#!/usr/bin/env zsh

action=$1
param1=$2
param2=$3

jarfile='/Users/xin.hao/avro-tools-1.10.1.jar'

cat() {
  java -jar $jarfile cat --offset 0 --limit 3 $param1 -
}

getschema() {
  java -jar $jarfile getschema $param1
}

tojson() {
  java -jar $jarfile tojson $param1
}

compile() {
  java -jar $jarfile compile schema $param1 $param2
}

usage() {
  echo Usage
  echo '  - cat'
  echo '  - getschema'
  echo '  - tojson'
  echo '  - compile'
}

case $action in
  cat)
    cat
  ;;
  compile)
    compile
  ;;
  getschema)
    getschema
  ;;
  tojson)
    tojson
  ;;
  *)
    usage
  ;;
esac
