#!/usr/bin/env zsh

# ls
cargo install exa --locked
# ps
cargo install procs --locked
# find
cargo install fd-find --locked
# grep
cargo install ripgrep --locked
# du
cargo install du-dust --locked

#
# Others
#

# Nushell
cargo install nu --locked
