#!/usr/bin/env zsh

# ls
cargo install exa --locked
# ps
cargo install procs --locked
# diff
cargo install difftastic --locked
# find
cargo install fd-find --locked
# grep
cargo install ripgrep --locked
# du
cargo install du-dust --locked
