#!/usr/bin/env zsh

action=$1
param1=$2
param2=$3

FLINK_DIR='/Users/xin.hao/Downloads/flink-1.12.0'

start() {
  cd $FLINK_DIR
  ./bin/start-cluster.sh
}

stop() {
  cd $FLINK_DIR
  ./bin/stop-cluster.sh
}

usage() {
  echo Usage
  echo '  - start'
  echo '  - stop'
  echo '  - run'
  echo '  - run_batch'
}

run() {
  echo TODO
}

run_batch() {
  echo TODO
}

case $action in
  start)
    start
  ;;
  stop)
    stop
  ;;
  run)
    run
  ;;
  run_batch)
    run_batch
  ;;
  *)
    usage
  ;;
esac
