#!/usr/bin/env node

const cp = require('child_process')
const { join } = require('path')
const fs = require('fs')

const USER_HX = 'haoxins'

let mode = 'normal'
let user = 'normal'

let params = process.argv.slice(2)

if (params.length !== 1) {
  quit()
}

if (!params[0].includes('/')) {
  quit()
}

params = params[0].split('/')
if (params.length !== 2) {
  quit()
}

let dir = params[0]
let repo = params[1]

let extra = ''
if (dir !== 'airwallex') {
  user = USER_HX
  extra = '-haoxins'
}

let dest = `git@github.com${extra}:${dir}/${repo}.git`
console.log('Clone: %s', dest)

const GITHUBDIR = process.env.GITHUBDIR

if (GITHUBDIR) {
  console.info('Go to: %s', GITHUBDIR)
  process.chdir(GITHUBDIR)
}

try {
  fs.accessSync('./' + dir)
  console.info('%s exists', dir)
} catch (e) {
  fs.mkdirSync(dir)
}

process.chdir('./' + dir)

try {
  fs.accessSync('./' + repo)
  console.info('%s/%s exists', dir, repo)
} catch (e) {
  clone()
}

function clone() {
  let result = cp.spawnSync('git', ['clone', dest])

  if (result.status) {
    console.error(result.stderr.toString())
  } else {
    console.info(result.stdout.toString())
  }

  if (user === USER_HX) {
    process.chdir('./' + repo)

    cp.spawnSync('git', ['config', 'user.email', '"haoxinst@gmail.com"'])
    cp.spawnSync('git', ['config', 'user.name', '"haoxin"'])

    result = cp.spawnSync('git', ['config', '--list', '--local'])

    if (result.status) {
      console.error(result.stderr.toString())
    } else {
      console.info(result.stdout.toString())
    }
  }
}

function quit() {
  console.error('Invalid params, quit')
  console.info('Usage: gitclone owner/repo')
  process.exit(1)
}
