#!/usr/bin/env python3

import sys
import os
from os import path
from subprocess import PIPE, run

if len(sys.argv) != 2:
    sys.exit("Invalid params")

param = sys.argv[1]

if "/" not in param:
    sys.exit("Invalid repo path, should be `owner/repo`")

[owner, repo] = param.split("/")

user = "haoxins"

dest = f"git@github.com:{owner}/{repo}.git"
print(f"Clone from: {dest}")

github_dir = os.getenv("GITHUB_DIR")

if github_dir == "":
    sys.exit("Please set env: GITHUB_DIR")

print(f"Go to dir: {github_dir}")
os.chdir(github_dir)

github_dir = path.join(github_dir, owner)
if not path.isdir(github_dir):
    os.mkdir(github_dir)

print(f"Go to dir: {github_dir}")
os.chdir(github_dir)

if path.isdir(path.join(github_dir, repo)):
    sys.exit(f"The {owner}/{repo} exists")

run(["git", "clone", dest])

os.chdir(path.join(github_dir, repo))

run(["git", "config", "user.email", "haoxinst@gmail.com"])
run(["git", "config", "user.name", "Xin Hao"])

print("The whole git config")
result = run(["git", "config", "--list", "--local"], stdout=PIPE)
print(result.stdout.decode())
