#!/usr/bin/env bash

action=$1

dir=`dirname $0`

. ${dir}/util/kit.sh

git_diff() {
  git add --all
  loglog 'status:'
  git status
  git diff
  git diff --cached
}

git_log() {
  git log --all --graph --abbrev-commit --date=relative --pretty=format:'%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset'
}

git_up() {
  git_diff
  echo
  git commit -a
  echo
  git push
}

git_status() {
  loglog 'all remotes:'
  git remote

  loglog 'all branches:'
  git branch

  loglog 'latest 5 tags:'
  git tag | tail -5

  loglog 'stash list:'
  git stash list

  loglog 'repo status:'
  git status -sb
}

usage() {
  echo gits status
  echo gits diff
  echo gits log
  echo gits up - 'gits diff && commit && push'
}

case $action in
  diff)
    git_diff
  ;;
  log)
    git_log
  ;;
  up)
    git_up
  ;;
  status)
    git_status
  ;;
  *)
    usage
  ;;
esac
