#!/usr/bin/env bash

msg=''

loglog() {
  echo
  echo ------------------------------------------------------------
  echo $msg
  echo
}

msg='all remotes:'
loglog
git remote

msg='all branches:'
loglog
git branch

msg='latest 5 tags:'
loglog
git tag | tail -5

msg='stash list:'
loglog
git stash list

msg='repo status:'
loglog
git status
