#!/usr/bin/env node

'use strict'

const { spawnSync } = require('child_process')
const { basename } = require('path')

const params = process.argv.slice(2)

const usage = `
Usage:
  gitupstream owner repo
  gitupstream owner
`

if (!params.length) {
  console.error('invalid params !')
  console.info(usage)
  process.exit(1)
}

const owner = params[0]
const repo = params[1] || basename(process.cwd())
const upstream = `git@github.com:${owner}/${repo}.git`

if (['--help', '-h'].includes(owner.trim())) {
  console.info(usage)
  process.exit(0)
}

checkUpstream()

console.info(`upstream is ${owner}/${repo}`)

addUpstream()

/**
 * utils
 */

function checkUpstream() {
  const result = spawnSync('git', ['remote'])

  if (result.status) {
    console.error(result.stderr.toString())
    process.exit(1)
  }

  if (result.stdout.toString().includes('upstream')) {
    console.error('remote - upstream exist !')
    process.exit()
  }
}

function addUpstream() {
  const result = spawnSync('git', ['remote', 'add', 'upstream', upstream])

  if (result.status) {
    console.error(result.stderr.toString())
  } else {
    console.info('upstream added !')
  }
}
