#!/usr/bin/env zsh

action=$1
param1=$2

info() {
  kubectl cluster-info
}

cluster() {
  kubectl config get-clusters
}

user() {
  kubectl config get-users
}

ctx() {
  kubectl config get-contexts
}

use_ctx() {
  kubectl config use-context $param1
}

ns() {
  kubectl get namespace
}

use_ns() {
  kubectl config set-context --current --namespace $param1
}

svc() {
  kubectl get svc
}

po() {
  kubectl get po
}

pv() {
  kubectl get pv
}

ev() {
  kubectl get ev
}

warn() {
  kubectl get ev --field-selector type=Warning
}

logs() {
  kubectl logs $param1
}

follow() {
  kubectl logs $param1 -f
}

desc() {
  kubectl describe po $param1
}

exec() {
  kubectl exec --stdin --tty $param1 -- /bin/bash
}

usage() {
  echo Usage
  echo '  - info'
  echo '  - cluster'
  echo '  - user'
  echo '  - ctx'
  echo '  - use_ctx $context'
  echo '  - ns'
  echo '  - use_ns $namespace'
  echo '  - svc'
  echo '  - po'
  echo '  - pv'
  echo '  - ev'
  echo '  - warn'
  echo '  - logs $pod'
  echo '  - follow $pod'
  echo '  - desc $pod'
  echo '  - exec $pod'
}

case $action in
  info)
    info
  ;;
  cluster)
    cluster
  ;;
  user)
    user
  ;;
  ctx)
    ctx
  ;;
  use_ctx)
    use_ctx
  ;;
  ns)
    ns
  ;;
  use_ns)
    use_ns
  ;;
  svc)
    svc
  ;;
  po)
    po
  ;;
  pv)
    pv
  ;;
  ev)
    ev
  ;;
  warn)
    warn
  ;;
  logs)
    logs
  ;;
  follow)
    follow
  ;;
  desc)
    desc
  ;;
  exec)
    exec
  ;;
  *)
    usage
  ;;
esac
