#!/usr/bin/env zsh

action=$1
param1=$2
param2=$3

info() {
  kubectl cluster-info
}

ctx() {
  kubectl config get-contexts
}

rm_ctx() {
  kubectl config delete-context $param1
}

use_ctx() {
  kubectl config use-context $param1
}

ns() {
  kubectl get namespace
}

use_ns() {
  kubectl config set-context --current --namespace $param1
}

pods() {
  kubectl get pods -o wide
}

logs() {
  kubectl logs $param1
}

exec() {
  kubectl exec --stdin --tty $param1 -- /bin/bash
}

port() {
  kubectl port-forward $param1 $param2
}

desc() {
  kubectl describe pods $param1
}

cluster() {
  kubectl config get-clusters
}

rm_cluster() {
  kubectl config delete-cluster $param1
}

user() {
  kubectl config get-users
}

rm_user() {
  kubectl config delete-user $param1
}

usage() {
  echo Usage
  echo '  - info'
  echo '  - ctx'
  echo '  - rm_ctx context'
  echo '  - use_ctx context'
  echo '  - ns'
  echo '  - use_ns namespace'
  echo '  - pods'
  echo '  - logs pod'
  echo '  - exec pod'
  echo '  - port pod local_port:pod_port'
  echo '  - desc pod'
  echo '  - cluster'
  echo '  - rm_cluster'
  echo '  - user'
  echo '  - rm_user'
}

case $action in
  info)
    info
  ;;
  ctx)
    ctx
  ;;
  use_ctx)
    use_ctx
  ;;
  rm_ctx)
    rm_ctx
  ;;
  ns)
    ns
  ;;
  use_ns)
    use_ns
  ;;
  pods)
    pods
  ;;
  logs)
    logs
  ;;
  exec)
    exec
  ;;
  port)
    port
  ;;
  desc)
    desc
  ;;
  cluster)
    cluster
  ;;
  rm_cluster)
    rm_cluster
  ;;
  user)
    user
  ;;
  rm_user)
    rm_user
  ;;
  *)
    usage
  ;;
esac
