#!/usr/bin/env zsh

action=$1
param1=$2
param2=$3

KAFKA_DIR=/Users/xin.hao/kafka_2.12-2.6.1/bin

start_zk() {
  cd $KAFKA_DIR
  ./zookeeper-server-start.sh ../config/zookeeper.properties
}

start() {
  cd $KAFKA_DIR
  ./kafka-server-start.sh ../config/server.properties
}

clean() {
  rm -rf /tmp/kafka-logs /tmp/zookeeper
}

usage() {
  echo Usage
  echo '  - start_zk'
  echo '  - start'
  echo '  - clean'
}

case $action in
  start_zk)
    start_zk
  ;;
  start)
    start
  ;;
  clean)
    clean
  ;;
  *)
    usage
  ;;
esac
