#!/usr/bin/env python3

from urllib.parse import unquote
from datetime import datetime
from base64 import b64decode
import sys

if len(sys.argv) == 1:
  sys.exit()

origin = sys.argv[1]

if origin.isdigit():
  # timestamp
  ts = int(origin)
  if ts > 1000000000000:
    ts = int(ts / 1000)
  print(datetime.fromtimestamp(ts).strftime('%Y-%m-%d %H:%M:%S'))
elif origin.find('%') != -1:
  # encodeuri
  print(unquote(origin))
elif origin.endswith('='):
  # base64
  print(b64decode(origin))
