#!/usr/bin/env bash

. util/kit.sh

loglog 'all the remotes:'
git remote

loglog 'all the branches:'
git branch

loglog 'all the no merged branches:'
git branch --no-merged

loglog 'try to fetch ...'
git fetch
echo 'finished'

loglog 'the latest five tags:'
git tag | tail -5

loglog 'the stash list:'
git stash list

loglog 'repo status:'
git status

cd ..
