#!/usr/bin/env python3

from pathlib import Path
import subprocess
import argparse
import os
# scpf -f ./a -d /home/u/a -u u -host xx.com -up
parser = argparse.ArgumentParser(description='use scp easily')
parser.add_argument('-f', help='the file path')
parser.add_argument('-d', help='the dest path')
parser.add_argument('-u', help='user name')
parser.add_argument('-host', help='host')
parser.add_argument('-p', type=int, help='port')
parser.add_argument('-up', help='upload')

args = parser.parse_args()

if os.path.isabs(args.f):
  source = args.f
else:
  source = os.path.abspath(args.f)

if os.path.isabs(args.d):
  dest = args.d
else:
  dest = os.path.abspath(args.d)

if args.u == None:
  upload = True
else:
  upload = False

if args.u == None:
  host = args.host
else:
  host = args.u + '@' + args.host

if upload:
  params = ['scp', source, host + ':' + dest]
else:
  params = ['scp', host + ':' + source, dest]

print(params)

subprocess.call(params)
