export ZSH="/Users/xin.hao/.oh-my-zsh"

ZSH_THEME="robbyrussell"

plugins=(
  git
)

source $ZSH/oh-my-zsh.sh

export PATH=$PATH:/Users/xin.hao/github/haoxins/tool
export PATH=$PATH:/Users/xin.hao/Library/Python/3.9/bin
export PATH=$PATH:/Users/xin.hao/go/bin

export JAVA_HOME=$(/usr/libexec/java_home -v 11)
export GITHUB_DIR=/Users/xin.hao/github
export SPRING_PROFILES_ACTIVE=local

# Modern CLIs
alias ls=exa
alias cat=bat
alias find=fd
alias http=xh
alias grep=rg
alias du=dust
alias ps=procs

alias pyf="yapf -i -r --style='{based_on_style: yapf}'"
alias py="python3.9"
alias g7="gradle clean ktlintFormat build -x test"

alias flink="~/flink-1.12.0/bin/flink"
alias up="docker-compose up"

# Google Cloud SDK
if [ -f '/Users/xin.hao/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/xin.hao/google-cloud-sdk/path.zsh.inc'; fi
if [ -f '/Users/xin.hao/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/xin.hao/google-cloud-sdk/completion.zsh.inc'; fi
