export ZSH="/Users/xin.hao/.oh-my-zsh"

ZSH_THEME="robbyrussell"

plugins=(
  git
)

source $ZSH/oh-my-zsh.sh

export PATH=$PATH:$HOME/go/bin
export PATH=$PATH:$HOME/.deno/bin
export PATH=$PATH:$HOME/github/haoxins/shell

export JAVA_HOME=$(/usr/libexec/java_home -v 17)
export GITHUB_DIR=$HOME/github
export SPRING_PROFILES_ACTIVE=local

# Modern CLIs
alias ls=exa
alias find=fd
alias grep=rg
alias du=dust
alias ps=procs

alias c=clear
alias k=kubectl

# K8s
alias kns=kubens
alias kctx=kubectx
alias kexec="k exec --stdin --tty"

alias serve="python3 -m http.server"
alias gitignore="echo .DS_Store > .gitignore"
alias ip="ifconfig | grep inet | grep netmask | grep broadcast | cut -d: -f2"

# gRPC debug
alias grpcdebug="export GRPC_TRACE=all GRPC_VERBOSITY=DEBUG"

export PATH="$HOME/Library/Python/3.10/bin:$PATH"
