#!/usr/bin/env bash

# just for dev

sudo apt-get update

sudo apt-get install -y build-essential

# zsh

sudo apt-get install -y zsh

wget https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh -O - | zsh

chsh -s `which zsh`

# nodejs

curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash -
sudo apt-get install -y nodejs

# golang

wget -qO- https://storage.googleapis.com/golang/go1.8.linux-amd64.tar.gz | tar -xvz -C /usr/local/

### add path /usr/local/go/bin and GOPATH/bin

# vim config

git clone https://github.com/amix/vimrc.git ~/.vim_runtime

sh ~/.vim_runtime/install_awesome_vimrc.sh
